# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 124bbe510abfb6d26415f846d1df150210e6093672984ffd6cd22de20c8039b16bdd43580943cf7f67643e72c1b1e12c6a8aab954612a66bf6f3d0bbd858fa9c

test:
  secret_key_base: 939268e6e3e5781b8449b9d023b934a3a8e8800ae2f70218effde8498ba33fbd48b9cab5a3c510d693707460a9614c11410419bfb2faec7db436d06d8c9c9183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
